### ISSUE TITLE
Milestone 5 Feedback

### ISSUE THREAD

**Issue by matthewconnell** [STAT547-UBC-2019-20/group_12_qiyangqd_xiaoyuanf#48]
Hi Group 12, here's my feedback for this milestone:

Bugs and usage issues:
- [x] You might want to think about disabling some of the interaction options in the heatmap. It’s very difficult to zoom in or out with the default options. Maybe just leave tooltips?
- [x] If you de-select all the check boxes, an error occurs.

Layout and interface:
- [x] It’s hard to tell which dates I’ve selected on the range slider. It would be nice if there were some text saying “You have selected ______ to ___________”
- [x] In the time series plot, why is PM2.5 in square brackets?
- [x] In the scatterplot, the title of the y-axis is a little cut off. This is not a huge problem, but it would nice if you could fix it.

Overall, very well done!

**Comment by qiyangqd** [comment]
Hi Matthew!
Thank you for the valuable suggestions! We have modified our dashboard as follows:
Bugs and usage issues:

Layout and interface:
- Added texts saying the time range that users have selected.
- The initial reason for "[PM2.5]" was to represent "PM2.5 concentration", yet it seems to be misleading. Thanks for reminding us! Therefore, now the title and y-axis are changed into "PM2.5 concentration".
